version: "3.3"
services:
  server:
    build: .
    container_name: server
    restart: always
    ports:
      - "80:5000"

  mysql-server:
    image: mysql:8.0.22
    container_name: mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: drive
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.4
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: test
    ports:
      - "5000:80"
